#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use BapCat\Router\Router;
use BapCat\Values\HttpMethod;

$router = new Router();

$router->get   ('', '',                 'var_dump');
$router->get   ('', 'users',            'var_export');
$router->get   ('', 'users/:user',      'ksort');
$router->delete('', 'users/:user',      'usort');

$router->dumpRoutes();

echo "\n\n";
echo $router->findActionForRoute(HttpMethod::GET(), '');
echo "\n\n";
echo $router->findActionForRoute(HttpMethod::GET(), 'users');
echo "\n\n";
echo $router->findActionForRoute(HttpMethod::GET(), 'users/1');
echo "\n\n";
echo $router->findActionForRoute(HttpMethod::DELETE(), 'users/1');
